### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by rao94583** [bazelbuild/tulsi#126]
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: fe94872e-4c5c-434e-8448-92600f92869d
DEBUG: Rule 'build_bazel_rules_swift' modified arguments {"commit": "02c0ceb0fd1e966710c3f803bfae5136909de197", "shallow_since": "1579622252 -0800"} and dropped ["branch"]
DEBUG: Rule 'build_bazel_apple_support' modified arguments {"commit": "501b4afb27745c4813a88ffa28acd901408014e4", "shallow_since": "1577729628 -0800"} and dropped ["branch"]
ERROR: /private/var/tmp/_bazel_rao/9d733ec4740a12632ad05faadd8c7917/external/build_bazel_rules_apple/apple/internal/testing/apple_test_bundle_support.bzl:303:9: name 'coverage_common' is not defined
ERROR: /private/var/tmp/_bazel_rao/9d733ec4740a12632ad05faadd8c7917/external/build_bazel_rules_apple/apple/internal/testing/apple_test_rule_support.bzl:201:9: name 'coverage_common' is not defined
ERROR: /private/var/tmp/_bazel_rao/9d733ec4740a12632ad05faadd8c7917/external/build_bazel_rules_swift/swift/internal/swift_library.bzl:207:9: name 'coverage_common' is not defined
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@bazel_skylib' (requested by nodes 'REPOSITORY:@bazel_skylib')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.JceSecurityManager.<clinit>(Unknown Source)
	at java.base/javax.crypto.Cipher.getConfiguredPermission(Unknown Source)
	at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Unknown Source)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(Unknown Source)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.<init>(Unknown Source)

**Comment by thii** [comment]
I think you need an unreleased Bazel to build it now, or lock your `rules_apple` and `rules_swift` in your `WORKSPACE` to some old revision.

**Comment by MHX792** [comment]
Any news on this?

**Comment by keith** [comment]
Make sure you're pointing to the newest release of rules_apple, rules_swift, and bazel, then this should work. please open a new issue if that isn't the case
