### ISSUE TITLE
Tulsi fails to build with bazel 1.1.0 due to positional dependencies

### ISSUE THREAD

**Issue by tmarkovich** [bazelbuild/tulsi#128]
With a clean copy of master aside from an xcode version bump, I am getting the following error:

```
╰─ ./build_and_run.sh
INFO: Writing tracer profile to '/private/var/tmp/_bazel_thomasmarkovich/a5f09f8f6f8436becdaf05bc6b10233f/command.profile.gz'
INFO: Build option --host_force_python has changed, discarding analysis cache.
ERROR: /private/var/tmp/_bazel_thomasmarkovich/a5f09f8f6f8436becdaf05bc6b10233f/external/build_bazel_rules_apple/apple/internal/BUILD:39:1: in environment_plist rule @build_bazel_rules_apple//apple/internal:environment_plist_macos:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_thomasmarkovich/a5f09f8f6f8436becdaf05bc6b10233f/external/build_bazel_rules_apple/apple/internal/BUILD", line 39
		environment_plist(name = 'environment_plist_macos')
	File "/private/var/tmp/_bazel_thomasmarkovich/a5f09f8f6f8436becdaf05bc6b10233f/external/build_bazel_rules_apple/apple/internal/environment_plist.bzl", line 39, in _environment_plist
		legacy_actions.run(ctx, <3 more arguments>)
	File "/private/var/tmp/_bazel_thomasmarkovich/a5f09f8f6f8436becdaf05bc6b10233f/external/build_bazel_rules_apple/apple/internal/utils/legacy_actions.bzl", line 88, in legacy_actions.run
		ctx.actions.run(<1 more arguments>)
	File "/private/var/tmp/_bazel_thomasmarkovich/a5f09f8f6f8436becdaf05bc6b10233f/external/build_bazel_rules_apple/apple/internal/utils/legacy_actions.bzl", line 88, in ctx.actions.run
		_kwargs_for_apple_platform(ctx, <1 more arguments>)
	File "/private/var/tmp/_bazel_thomasmarkovich/a5f09f8f6f8436becdaf05bc6b10233f/external/build_bazel_rules_apple/apple/internal/utils/legacy_actions.bzl", line 63, in _kwargs_for_apple_platform
		execution_requirement_dicts.append(<1 more arguments>)
	File "/private/var/tmp/_bazel_thomasmarkovich/a5f09f8f6f8436becdaf05bc6b10233f/external/build_bazel_rules_apple/apple/internal/utils/legacy_actions.bzl", line 63, in execution_requirement_dicts.append
		apple_support.action_required_execution_requirements(<1 more arguments>)
_action_required_execution_requirements() does not accept positional arguments, but got 1
ERROR: Analysis of target '//:tulsi' failed; build aborted: Analysis of target '@build_bazel_rules_apple//apple/internal:environment_plist_macos' failed; build aborted
INFO: Elapsed time: 4.914s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (43 packages loaded, 439 targets configured)
```

It appears that maybe Tulsi just isn't compatiable with this version of bazel?

**Comment by tmarkovich** [comment]
It looks like Tulsi builds with bazel 2.1.0. I'll just use this as an excuse to upgrade...
