### ISSUE TITLE
Generating project fails with java.lang.OutOfMemoryError during config selection

### ISSUE THREAD

**Issue by robbertvanginkel** [bazelbuild/tulsi#14]
I'm trying to generate a Tulsi project for a codebase of mixed objective-c and swift targets. I'm using the new rules from the rules_apple repo.

For a smaller target with less dependencies, the project generates fine. However, when I select a target with more dependencies, bazel seems to fail with an out of memory error when I'm at the step where am going to select which source files I'd like to include in the project:
```
$ /private/var/tmp/_bazel_robbertvanginkel/06193c58a6c4b4a5fa1cd4f2ecd8b993/execroot/bazel/bazel-out/local-fastbuild/bin/src/bazel build -c dbg --symlink_prefix tulsigen- --announce_rc --nocheck_visibility --show_result=0 --package_path=%workspace%:/Users/robbertvanginkel/Library/Developer/Xcode/DerivedData/Tulsi-euigzcmqdbsljjdltfifpksghqom/Build/Products/Debug/Tulsi.app/Contents/Frameworks/TulsiGenerator.framework/Resources --aspects /tulsi/tulsi_aspects.bzl%tulsi_sources_aspect --output_groups=tulsi-info,-_,-default --experimental_show_artifacts //path/to/App:App
..........
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=209
INFO: Reading options for 'build' from /Users/robbertvanginkel/Uber/mobile/ios/tools/bazel.rc:
  'build' options: --ios_minimum_os=8.0
INFO: Elapsed time: 284.662s
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$9.printJson(SkylarkRuleClassFunctions.java:991)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$9.printJson(SkylarkRuleClassFunctions.java:977)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$9.printJson(SkylarkRuleClassFunctions.java:986)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$9.printJson(SkylarkRuleClassFunctions.java:977)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$9.invoke(SkylarkRuleClassFunctions.java:958)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:155)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:619)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:716)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:702)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:675)
	at com.google.devtools.build.lib.syntax.FuncallExpression.invokeObjectMethod(FuncallExpression.java:715)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:702)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:43)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.doExec(ExpressionStatement.java:40)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:81)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:428)
	at com.google.devtools.build.lib.skyframe.SkylarkAspectFactory.create(SkylarkAspectFactory.java:75)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:358)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:441)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:299)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:381)
Java heap space

bazel ran out of memory and crashed.
```
If I `bazel build //path/to/App:App` then bazel runs without memory issues and builds the app. I've also tried to increase the available jvm memory. Previously this seemed to fail when the java process was using ~4GB of memory. I tried doubling the available amount by adding `--host_jvm_args=-Xmx8g` to the command, but it still fails.

**Comment by dmishe** [comment]
@robbertvanginkel do you have a lot of small targets, or few targets that contain lots of sources?

It looks like Java's string builder cannot handle the amount of structs() that are turned into json in Skylark. During project generation, Tulsi is running an aspect over the build graph and captures relevant information into a struct, that then gets written out as JSON https://github.com/bazelbuild/tulsi/blob/master/src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl#L550

@dslomov would you be able to help us narrow this down?

**Comment by dslomov** [comment]
Could it be that your info structs grow as O(n^2)? `swift_transitive_modules` seem particularly suspect.

**Comment by robbertvanginkel** [comment]
The target I'm building has ~170 deps. About 5 are relatively large, with >200 source files, the rest is smaller with ~50 on average.

It seems to start happening with a swift library in the tree that has a lot of dependencies. I've tried and I can generate projects for some (haven't tried all) of the dependencies, but the swift library with ~80 dependencies seems to be the point at which this starts.

**Comment by dmishe** [comment]
Yep looks like we forgot to switch lists to sets in swift library rule, I
will send a fix shortly

**Comment by dslomov** [comment]
if it is about the info struct then just switching to depsets won't help

**Comment by dmishe** [comment]
I thought that is why you pointed out swift_transitive_modules. Or was it because it generates a small struct for each entry in swift_transitive_modules? 

For a library with 80 deps, the info struct will indeed have 80 substructs in that list. It's 2 strings and 2 bools per struct. 

I think I can generate a benchmark graph to try to surface this in detail.

**Comment by dslomov** [comment]
If I understand [this line](https://github.com/bazelbuild/tulsi/blob/master/src/TulsiGenerator/Bazel/tulsi/tulsi_aspects.bzl#L576), correctly, info struct for EVERY target contains swift modules for ALL its transitive dependencies. I.e. for N targets in transitive closure you will have N info structs, each with O(N) items in `swift_transitive_modules`. All these structs live in memory (because they are a part of action graph), so you get O(N^2) memory for your build.

**Comment by dmishe** [comment]
Yes you're right, each target would keep a copy of all modules in its closure. Though I wouldn't expect build graphs to get that interconnected where each target is related to N-1 other targets.  

In my testing, having 6400 (80^2 from the aforementioned smallest repro case) swift_library targets works fine, even though it takes 13 minutes and 8GB of ram from JVM. 10000 targets kills it, though. It may be possible that modules alone do not push over the limit, but other pieces of data in the info struct do. One possible suspect is objc module maps, which each target accumulates from ObjcProvider.

@robbertvanginkel I have pushed a [change](https://github.com/bazelbuild/rules_apple/pull/31) to use depsets in appropriate places and it should reduce the memory pressure a little. Could you test?

**Comment by dmishe** [comment]
Ugh, my apologies, the change had to be rolled back.

**Comment by dmishe** [comment]
Some minor depset optimizations in https://github.com/bazelbuild/rules_apple/commit/59a205f35d4da35ea3a1111bf8ae2e82867d86cf should fix this. 

@robbertvanginkel verified.
