### ISSUE TITLE
Tulsi CI broken on buildkite

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/tulsi#215]
Tulsi project CI is broken both for Bazel@HEAD and release Bazel.

Sample failure:
https://buildkite.com/bazel/tulsi-bazel-darwin/builds/1242#e81aa8f7-90da-4098-b6b7-4942a0c198e8

Has been broken since Jan 28.

Log snippet:

```
> W: Failed to clean cache of dSYMs, clean script returned error code 1, Traceback (most recent call last):
  File "/tmp/test_tmp_dir.rSoTWa/EndToEndGenerationTests.xctest/Contents/Resources/clean_symbol_cache.py", line 56, in <module>
    CleanSymbolCache().CleanMissingDSYMs()
  File "/tmp/test_tmp_dir.rSoTWa/EndToEndGenerationTests.xctest/Contents/Resources/clean_symbol_cache.py", line 52, in __init__
    self.cache_schema = SymbolCacheSchema(db_path)
  File "/private/tmp/test_tmp_dir.rSoTWa/EndToEndGenerationTests.xctest/Contents/Resources/symbol_cache_schema.py", line 115, in __init__
    self.connection = self.InitDB(db_path)
  File "/private/tmp/test_tmp_dir.rSoTWa/EndToEndGenerationTests.xctest/Contents/Resources/symbol_cache_schema.py", line 101, in InitDB
    os.makedirs(os.path.dirname(db_path))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/Users/buildkite/Library/Application Support/Tulsi'
Exception AttributeError: "'SymbolCacheSchema' object has no attribute 'connection'" in <bound method SymbolCacheSchema.__del__ of <symbol_cache_schema.SymbolCacheSchema object at 0x107d44510>> ignored
.
Test Case '-[src_TulsiGeneratorIntegrationTests_EndToEndGenerationTests_lib.TestSuiteEndToEndGenerationTests test_TestSuiteRecursiveTestSuiteProject]' passed (1.101 seconds).
Test Suite 'TestSuiteEndToEndGenerationTests' passed at 2021-01-29 09:25:45.620.
	 Executed 3 tests, with 0 failures (0 unexpected) in 3.368 (3.369) seconds
Test Suite 'EndToEndGenerationTests.xctest' failed at 2021-01-29 09:25:45.620.
	 Executed 14 tests, with 33 failures (0 unexpected) in 47.738 (47.742) seconds
Test Suite 'All tests' failed at 2021-01-29 09:25:45.621.
	 Executed 14 tests, with 33 failures (0 unexpected) in 47.738 (47.743) seconds
```

**Comment by thii** [comment]
Related: https://github.com/bazelbuild/continuous-integration/issues/1073 cc @philwo

**Comment by philwo** [comment]
I'll roll out new Xcode versions this evening.
