### ISSUE TITLE
bazel_cache_reader buile error

### ISSUE THREAD

**Issue by boundlessocean** [bazelbuild/tulsi#234]
How can i resovle this problem?

/tulsi/src/tools/bazel_cache_reader/BUILD:15:31: in macos_command_line_application rule //src/tools/bazel_cache_reader:bazel_cache_reader: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_fuhaiyang/912515b77de5d7cd7965e30205f5d200/external/build_bazel_rules_apple/apple/internal/macos_rules.bzl", line 1182, column 58, in _macos_command_line_application_impl
		link_result = linking_support.register_linking_action(
	File "/private/var/tmp/_bazel_fuhaiyang/912515b77de5d7cd7965e30205f5d200/external/build_bazel_rules_apple/apple/internal/linking_support.bzl", line 102, column 47, in _register_linking_action
		return apple_common.link_multi_arch_binary(
Error in link_multi_arch_binary: link_multi_arch_binary() got unexpected keyword argument 'stamp'
ERROR: Analysis of target '//:tulsi' failed; build aborted: Analysis of target '//src/tools/bazel_cache_reader:bazel_cache_reader' failed
INFO: Elapsed time: 13.328s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (48 packages loaded, 527 targets c\
onfigured)

**Comment by thii** [comment]
Looks like you were using an older Bazel version? You will need Bazel 4.0 to build Tulsi now.

**Comment by omarzl** [comment]
I had the same error, using Bazel 4.0 it compiled fine
