### ISSUE TITLE
Tulsi is broken with Bazel@HEAD

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/tulsi#248]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2054#a3c4d5f1-74ed-4a5a-9b88-aa6765e6de16

```
(04:12:51) ERROR: /Users/buildkite/builds/bk-imacpro-10/bazel-downstream-projects/tulsi/src/TulsiGenerator/BUILD:30:14: in swift_library rule //src/TulsiGenerator:tulsi_generator_lib:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/48642d6e04617858cf3f352a19d2fae8/external/build_bazel_rules_swift/swift/internal/swift_library.bzl", line 284, column 43, in _swift_library_impl
		providers.append(new_objc_provider(
	File "/private/var/tmp/_bazel_buildkite/48642d6e04617858cf3f352a19d2fae8/external/build_bazel_rules_swift/swift/internal/compiling.bzl", line 2397, column 42, in new_objc_provider
		return apple_common.new_objc_provider(**objc_provider_args)
Error in new_objc_provider: Argument uses_swift not a recognized key, 'strict_include', or 'providers'.
```

**Comment by keith** [comment]
Thanks yep, I need to fix with a new release of rules_apple

**Comment by cpsauer** [comment]
I'm still seeing this error with the latest Tulsi (commit: 63bab0d), rules_apple 0.31.3, and Bazel rolling (5.0.0-pre.20210929.1).
That's unexpected, right?
