### ISSUE TITLE
XCode 12.5 support

### ISSUE THREAD

**Issue by SamuelMarks** [bazelbuild/tulsi#271]
```
./build_and_run.sh 
Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/82634976f2152a907e181771fce8c4e0/external/local_config_xcode/BUILD:12:13: in xcode_config rule @local_config_xcode//:host_xcodes: --xcode_version=12.4 specified, but '12.4' is not an available Xcode version. available versions: [12.5.1.12E507]. If you believe you have '12.4' installed, try running "bazel shutdown", and then re-run your command.
INFO: Repository rules_java instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:269:6: in <toplevel>
  /private/var/tmp/82634976f2152a907e181771fce8c4e0/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /private/var/tmp/82634976f2152a907e181771fce8c4e0/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//:tulsi' failed; build aborted: Analysis of target '@local_config_xcode//:host_xcodes' failed
INFO: Elapsed time: 18.436s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (36 packages loaded, 186 targets configured)
    currently loading: @bazel_tools//tools/jdk
    Fetching @local_config_cc; fetching
    Fetching @local_config_cc_toolchains; fetching
```

Tried cheating `fastmod -F '12.4' '12.5'` (`find -type f -exec sed -i 's/12\.4/12\.5/g' {} \;`):
```
INFO: Build option --xcode_version has changed, discarding analysis cache.
ERROR: repos/tulsi/src/tools/bazel_cache_reader/BUILD:15:31: in macos_command_line_application rule //src/tools/bazel_cache_reader:bazel_cache_reader: 
Traceback (most recent call last):
	File "/private/var/tmp/82634976f2152a907e181771fce8c4e0/external/build_bazel_rules_apple/apple/internal/macos_rules.bzl", line 1192, column 58, in _macos_command_line_application_impl
		link_result = linking_support.register_linking_action(
	File "/private/var/tmp/82634976f2152a907e181771fce8c4e0/external/build_bazel_rules_apple/apple/internal/linking_support.bzl", line 103, column 47, in _register_linking_action
		return apple_common.link_multi_arch_binary(
Error in link_multi_arch_binary: link_multi_arch_binary() got unexpected keyword argument 'stamp'
ERROR: Analysis of target '//:tulsi' failed; build aborted: Analysis of target '//src/tools/bazel_cache_reader:bazel_cache_reader' failed
INFO: Elapsed time: 4.917s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 518 targets configured)
```

So I think it needs something more. 12.5 has been out since 26 Apr 2021…

**Comment by wendyliga** [comment]
@SamuelMarks you can change the version by passing `-x`

```
build_and_run.sh -x 12.5
```

**Comment by ivanhernandez13** [comment]
Make sure your Apple BUILD rules checkout in your WORKSPACE file are up to date. Using an old version of the rules can cause build failures like this one.

https://github.com/bazelbuild/tulsi/blob/master/WORKSPACE

**Comment by SamuelMarks** [comment]
@wendyliga Same error (after a `git reset --hard`):
> Error in link_multi_arch_binary: `link_multi_arch_binary()` got unexpected keyword argument 'stamp'

@ivanhernandez13 This is from a fresh `git clone https://github.com/bazelbuild/tulsi`

**Comment by DavidGoldman** [comment]
Please re-open if you're still seeing this - likely the rules_apple/rules_swift checkouts are not in sync with your Bazel version.
