### ISSUE TITLE
Failure to install Tulsi (Xcode 14.1 System 13.0.1)

### ISSUE THREAD

**Issue by Roger-LP** [bazelbuild/tulsi#393]
luoping@luopingdeMacBook-Pro tulsi % sh build_and_run.sh
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:tulsi (73 packages loaded, 1216 targets configured).
INFO: Found 1 target...
[90 / 109] 3 actions running
    StoryboardCompile tulsi-intermediates/Base.lproj_storyboardc/Main.storyboardc; 4s local
    CompileRootInfoPlist tulsi-intermediates/Info.plist; 0s darwin-sandbox
    Linking external/build_bazel_rules_swift/tools/worker/worker; 0s darwin-sandbox
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.NoSuchMethodError: java.lang.Process.pid()J
	at com.google.devtools.build.lib.shell.JavaSubprocessFactory$JavaSubprocess.getProcessId(JavaSubprocessFactory.java:118)
	at com.google.devtools.build.lib.worker.SingleplexWorker.getProcessId(SingleplexWorker.java:196)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.initializeMetricsSet(WorkerSpawnRunner.java:540)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:404)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:207)
	at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:245)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:146)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:108)
	at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:68)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:328)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:907)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1076)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1031)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:492)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
