### ISSUE TITLE
Tulsi broken with bazel HEAD

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/tulsi#86]
When building tulsi with Bazel from `HEAD` we get the following error

Tulsi at 3dd59abc8d82e64b9ea35127b180318c87752afe

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/928#96658a3e-b010-4e66-b96f-e8ef8ce7ac8e

```
ERROR: /Users/buildkite/builds/buildkite-imacpro-5/bazel-downstream-projects/tulsi/src/tools/bazel_cache_reader/BUILD:7:1: in @build_bazel_rules_apple//apple/internal/aspects:resource_aspect.bzl%apple_resource_aspect aspect on objc_library rule //src/tools/bazel_cache_reader:bazel_cache_reader_lib:
--
  | Traceback (most recent call last):
  | File "/Users/buildkite/builds/buildkite-imacpro-5/bazel-downstream-projects/tulsi/src/tools/bazel_cache_reader/BUILD", line 7
  | @build_bazel_rules_apple//apple/internal/aspects:resource_aspect.bzl%apple_resource_aspect(...)
  | File "/private/var/tmp/_bazel_buildkite/5b34b79d6807e992662bc230e3ced2c5/external/build_bazel_rules_apple/apple/internal/aspects/resource_aspect.bzl", line 73, in _apple_resource_aspect_impl
  | providers.extend([x[AppleResourceInfo] for x in c...])
  | File "/private/var/tmp/_bazel_buildkite/5b34b79d6807e992662bc230e3ced2c5/external/build_bazel_rules_apple/apple/internal/aspects/resource_aspect.bzl", line 75, in providers.extend
  | ctx.rule.attr.bundles
  | No attribute 'bundles' in attr. Make sure you declared a rule attribute with this name.
  | Available attributes: _action_listener, _apple_sdk, _cc_toolchain, _cc_toolchain_type, _config_dependencies, _header_scanner, _libtool, _xcode_config, _xcrunwrapper, alwayslink, compatible_with, copts, data, defines, deprecation, deps, enable_modules, features, generator_function, generator_location, generator_name, hdrs, includes, licenses, module_map, module_name, name, non_arc_srcs, pch, restricted_to, runtime_deps, sdk_dylibs, sdk_frameworks, sdk_includes, srcs, tags, testonly, textual_hdrs, toolchains, transitive_configs, visibility, weak_sdk_frameworks
  | WARNING: errors encountered while analyzing target '//:tulsi': it will not be built
```

I ll disable downstream testing of tulsi until it's resolved. Thanks!

**Comment by meteorcloudy** [comment]
Related issue: https://github.com/bazelbuild/bazel/issues/8084

**Comment by meteorcloudy** [comment]
The project is disabled in [Bazel's downstream test](https://buildkite.com/bazel/bazel-at-head-plus-downstream) due to this issue, please help fixing.

**Comment by DavidGoldman** [comment]
Is there a more recent error that I can look at?

**Comment by meteorcloudy** [comment]
With Bazel 0.25.2: https://buildkite.com/bazel/tulsi-bazel-darwin/builds/143
With Bazel@HEAD: https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/181#69d3bcd5-29b0-4376-a7d8-2f74281c9349

**Comment by DavidGoldman** [comment]
looks like this is now fixed

**Comment by hlopko** [comment]
Great, thank you! I'll enable tulsi on Bazel CI now.

**Comment by wesj** [comment]
I ran into this because the tutorial documentation suggests importing the apple build rules tag = "0.13.0". For anyone digging, I updated my WORKSPACE to the latest from https://github.com/bazelbuild/rules_apple/releases to fix it.
